pipeline {
    /* agent {
        docker {
            image 'docker:latest'
            args '-v /root/.m2:/root/.m2'
        }
    } */
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'docker login -u amelkinaf -p dckr_pat_-vZPcc25G17XlKPzszocLeR-eeg'
                sh 'docker build build/app1 --tag amelkinaf/httpd:2.0'
                sh 'docker push amelkinaf/httpd:2.0'
            }
        }
    }
}