pipeline {
    /* agent {
        docker {
            image 'docker:latest'
            args '-v /root/.m2:/root/.m2'
        }
    } */
    agent any
    stages {
        stage('Build') {
            steps {
                withCredentials([
                    string(credentialsId: 'DOCKER_REGISTRY_TOKEN', variable: 'DOCKER_REGISTRY_TOKEN')
                ]) {
                    sh 'docker login -u amelkinaf -p $DOCKER_REGISTRY_TOKEN'
                }
                sh 'docker build build/app1 --tag amelkinaf/httpd:3.0'
                sh 'docker push amelkinaf/httpd:3.0'
            }
        }
    }
}